kind: Deployment
apiVersion: apps/v1
metadata:
  name: d-payhub-fe
  namespace: dev
  labels:
    app: proxy-payhub-fe
    env: dev
spec:
  replicas: 1
  selector:
    matchLabels:
      app: d-payhub-fe
      env: dev
  template:
    metadata:
      labels:
        app: d-payhub-fe
        env: dev
    spec:
      containers:
        - name: d-payhub-fe
          image: 'images.247.or.id/pandi/payment-aggregator-frontend:latest'
          ports:
            - name: http
              containerPort: 80
              protocol: TCP
        #  volumeMounts:
     #       - name: d-payhubndimeeting-frontendenv
      #        mountPath: /usr/share/nginx/html/.env
       #       subPath: .env
          imagePullPolicy: Always
      restartPolicy: Always
      imagePullSecrets:
        - name: secret-dev